name = "OnlinePackage"
uuid = "dec300e5-7e5b-577b-bc13-c7c11ad250bc"
author = ["Brandon Taylor <brandon.taylor221@gmail.com>"]
repo = "https://github.com/bramtayl/OnlinePackage.jl.git"
version = "0.2.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
libsodium_jll = "a9144af2-ca23-56d9-984f-0d03f7b5ccf8"

[compat]
HTTP = "0.8.8"
JSON = "0.21.0"
julia = "1.3"
libsodium_jll = "1.0.18"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter"]
